In [1]:
import igl
import numpy as np
from src.ms_new import MorseSmale
from src import vis

from tqdm.notebook import tqdm

In [2]:
import pyvista as pv

from src import shapes

In [3]:
f_dist = lambda p: np.linalg.norm(p, axis=-1, ord=2)
f_linear = lambda p: p[:, 1]

n, m = 13, 12
vertices, faces = shapes.get_halftori_bouquet(leaves=3, n=n, m=m, l0=0.9, glue=False)

values = f_dist(vertices)
#values = f_linear(vertices)

print(f'vertices.shape = {vertices.shape}')
print(f'faces.shape = {faces.shape}')
print(f'values.shape = {values.shape}')


vertices.shape = (502, 3)
faces.shape = (1008, 3)
values.shape = (502,)


In [4]:
import pickle as pkl

with open('data/hard-goat.pkl', 'rb') as file:
    vertices, faces, values = pkl.load(file)


print(f'vertices.shape = {vertices.shape}')
print(f'faces.shape = {faces.shape}')
print(f'values.shape = {values.shape}')

vertices.shape = (2150, 3)
faces.shape = (3998, 3)
values.shape = (2150,)


In [ ]:
mesh = vis.get_pv_mesh(vertices, faces)

pl = pv.Plotter(window_size=(600, 600))
pl.add_mesh(mesh, scalars=values, cmap="viridis", smooth_shading=False, show_edges=True, opacity=1.0)
pl.show()

Widget(value='<iframe src="http://localhost:32847/index.html?ui=P_0x7bcb39219eb0_0&reconnect=auto" class="pyvi…

 JS Error => TypeError: Cannot create proxy with a non-object as target or handler
 JS Error => TypeError: Cannot create proxy with a non-object as target or handler
 JS Error => TypeError: Cannot create proxy with a non-object as target or handler


In [6]:
ms = MorseSmale(faces=faces, values=values, vertices=vertices)

In [7]:
(ms.local_maxima, ms.local_minima, ms.saddles)

(array([   0,  224,  534, 1130, 1694, 2107, 2120, 2137]),
 array([  80,  196,  523, 1058, 1176, 1199, 1778, 1897, 2089]),
 array([  54,   71,  158,  449,  489,  525,  931,  977, 1003, 1148, 1270,
        1350, 1451, 1564, 1921, 2013, 2129]))

In [8]:
print(f'local_maxima: {len(ms.local_maxima)}')
print(f'local_minima: {len(ms.local_minima)}')
print(f'saddles: {len(ms.saddles)}')

local_maxima: 8
local_minima: 9
saddles: 17


In [9]:
ms.saddles

array([  54,   71,  158,  449,  489,  525,  931,  977, 1003, 1148, 1270,
       1350, 1451, 1564, 1921, 2013, 2129])

In [10]:
print(f'          ms.local_maxima  = {ms.local_maxima}\nms.values[ms.local_maxima] = {ms.values[ms.local_maxima]}')
print(f'          ms.local_minima  = {ms.local_minima}\nms.values[ms.local_minima] = {ms.values[ms.local_minima]}')
print(f'          ms.saddles  = {ms.saddles}\nms.values[ms.saddles] = {ms.values[ms.saddles]}')


          ms.local_maxima  = [   0  224  534 1130 1694 2107 2120 2137]
ms.values[ms.local_maxima] = [ 1.          0.97929624  0.99043239  0.99876966 -0.2022893   1.
  0.99996618  0.9999514 ]
          ms.local_minima  = [  80  196  523 1058 1176 1199 1778 1897 2089]
ms.values[ms.local_minima] = [-0.98801457 -1.00656034 -1.00524038 -1.00660782 -1.00590338 -1.00164579
 -1.00636823 -1.52792293 -0.69119076]
          ms.saddles  = [  54   71  158  449  489  525  931  977 1003 1148 1270 1350 1451 1564
 1921 2013 2129]
ms.values[ms.saddles] = [-0.9813481   0.59429978 -0.99989386 -0.27504044 -0.99857391  0.36964455
 -0.87721937 -0.68711423 -0.25429362 -0.99497931 -0.94130074 -0.45005335
 -0.20907633  0.87358264 -0.99923691 -0.99970176 -0.99994135]


In [11]:
ms.get_directions_queue(how='increasing-decreasing')

deque([(54, np.int32(35)),
       (54, np.int32(55)),
       (71, np.int32(48)),
       (71, np.int32(102)),
       (158, np.int32(122)),
       (158, np.int32(195)),
       (449, np.int32(477)),
       (449, np.int32(431)),
       (489, np.int32(426)),
       (489, np.int32(524)),
       (525, np.int32(472)),
       (525, np.int32(546)),
       (931, np.int32(856)),
       (931, np.int32(1014)),
       (977, np.int32(898)),
       (977, np.int32(978)),
       (1003, np.int32(1002)),
       (1003, np.int32(1004)),
       (1148, np.int32(1069)),
       (1148, np.int32(1282)),
       (1270, np.int32(1188)),
       (1270, np.int32(1346)),
       (1350, np.int32(1274)),
       (1350, np.int32(1423)),
       (1451, np.int32(1376)),
       (1451, np.int32(1475)),
       (1564, np.int32(1593)),
       (1564, np.int32(1823)),
       (1921, np.int32(1899)),
       (1921, np.int32(2111)),
       (2013, np.int32(2086)),
       (2013, np.int32(2145)),
       (2129, np.int32(1960)),
       (2129, n

In [12]:
ms.get_paths()

Searching paths:   2%|▏         | 1/61 [00:00<00:00, 90.90it/s, Returned directions=set()] /home/fzimin/Projects/Rotation 2 - Chris Wojtan'/quadrangulation/.venv/lib/python3.12/site-packages/scipy/sparse/_index.py:155: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil and dok are more efficient.
  self._set_intXint(row, col, x.flat[0])
Searching paths: 62it [02:37,  2.55s/it, Returned directions=set()]                        


[array([54, 35, 36, 21, 19, 11,  6,  5,  3,  0]),
 array([ 54,  55,  45,  44,  66,  95,  98, 114, 148, 224]),
 array([71, 48, 30, 16,  8,  2,  0]),
 array([  71,  102,  136,  157,  194,  234,  273,  314,  362,  410, 1930,
        2120]),
 array([158, 122,  88,  62,  41,  25,  15,   7,   1,   0]),
 array([158, 195, 275, 317, 365, 414, 462, 512, 534]),
 array([449, 477, 519, 571, 570, 535, 569, 568, 567, 566, 565, 534]),
 array([ 449,  431,  381,  358,  354,  353,  355,  356,  357,  359,  360,
         409,  410, 1930, 2120]),
 array([489, 426, 392, 391, 345, 289, 304, 263, 224]),
 array([ 489,  524,  576,  626,  683,  745,  813,  886, 1047, 1130]),
 array([525, 472, 423, 394, 346, 300, 260, 223, 207, 224]),
 array([ 525,  546,  486,  483,  436,  437,  389,  370,  335,  336,  316,
         363,  411,  410, 1930, 2120]),
 array([ 931,  856,  787,  722,  662,  606,  555,  553,  554,  556,  505,
         455,  456, 1834, 1835, 2016, 1930, 2120]),
 array([ 931, 1014, 1093, 1173, 1254, 1333, 

In [13]:
pl = pv.Plotter(window_size=(600, 600))
pl.add_mesh(
    mesh,
    scalars=values,
    cmap="viridis",
    smooth_shading=False,
    show_edges=True,
    opacity=1.0,
)

for path in ms.get_paths():
    path_vertices = ms.vertices[path]

    line = pv.lines_from_points(path_vertices)
    pl.add_mesh(
        line,
        color="white",
        line_width=6,
        render_lines_as_tubes=True,
    )

pl.add_points(
        ms.vertices[ms.local_minima],
        color="lime",
        point_size=12,
        render_points_as_spheres=True,
)

pl.add_points(
        ms.vertices[ms.local_maxima],
        color="red",
        point_size=12,
        render_points_as_spheres=True,
)

pl.add_points(
        ms.vertices[ms.saddles],
        color="orchid",
        point_size=12,
        render_points_as_spheres=True,
)


pl.show()

Widget(value='<iframe src="http://localhost:32847/index.html?ui=P_0x7bca93886ea0_1&reconnect=auto" class="pyvi…

In [14]:
pl = pv.Plotter(window_size=(600, 600))
pl.add_mesh(
    mesh,
    scalars=values,
    cmap="viridis",
    smooth_shading=False,
    show_edges=True,
    opacity=1.0,
)


pl.add_points(
        ms.vertices[ms.local_minima],
        color="lime",
        point_size=12,
        render_points_as_spheres=True,
)

pl.add_points(
        ms.vertices[ms.local_maxima],
        color="red",
        point_size=12,
        render_points_as_spheres=True,
)

pl.add_points(
        ms.vertices[ms.saddles],
        color="orchid",
        point_size=12,
        render_points_as_spheres=True,
)


for path_vertices in tqdm(ms.iterate_paths_close_geodesics(), total=ms.n_paths):
    line = pv.lines_from_points(path_vertices)
    pl.add_mesh(
        line,
        color="white",
        line_width=6,
        render_lines_as_tubes=True,
    )


pl.show()

  0%|          | 0/61 [00:00<?, ?it/s]

Widget(value='<iframe src="http://localhost:32847/index.html?ui=P_0x7bca9399d9d0_2&reconnect=auto" class="pyvi…